#应用名
spring:
  application:
    name: eureka-server
  profiles:
    active: yml8280
# 端口号
server:
  port: 8280
# eureka配置
eureka:
  instance:
    hostname: eureka2
  client:
    fetch-registry: false # 禁止到Eureka器中获取注册信息
    register-with-eureka: false # 禁止将自己作为客户端注册信息到Eureka服务器
    serviceUrl:
      defaultZone: http://eureka0:8080/eureka/,http://eureka1:8180/eureka/