#应用名
spring:
  application:
    name: eureka-consumer
# 端口号
server:
  port: 8082
# eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka0:8080/eureka/,http://eureka1:8180/eureka/,http://eureka2:8280/eureka/ # 服务的注册发现地址
